### ISSUE TITLE
[For Semver] Announcement Center 1.2.1

### ISSUE THREAD

**Issue by PVince81** [owncloud/announcementcenter#102]
### Reason
- Core switching to Semver https://github.com/owncloud/core/pull/33242

### QA
- [x] Create **QA Milestone**
- [x] Move items from `development` to `qa` 
- [x] Create release branch release-1.2.1
- [x] Test: Install from the provided tarball and enable in ownCloud stable10 and check it works

### Documentation
- [x] Changes in the docs needed? => none

### Marketing
- [ ] Ping RocketChat channel #marketing
- [ ] Check/adapt info.xml stuff
- [ ] Check/adapt screenshot
- [ ] Blog post or other communication if applicable

### Build & Marketplace release

All actions to be done on the release branch from here:
- [x] Bump version in info.xml => https://github.com/owncloud/announcementcenter/pull/103
- [x] Update CHANGELOG.md - Change CHANGELOG.md 'Unreleased' to '$version - $currentDate' (ex: 3.1.5 - 2018-08-01) => https://github.com/owncloud/announcementcenter/pull/103
- [x] Create github tag for 'v${version}RC1'
- [x] Build and sign RC tarball from github tag 'v${version}RC1' with `make dist` => https://cloud.owncloud.com/index.php/s/W9CibdXbigggLUD
- [x] Test and document in testplan => Final "Go" from QA (set 'QA-ready' label) => else do another RC after fixing
- [x] Create github tag for final 'v${version}'
- [x] Build and sign final tarball from github tag 'v${version}' with `make dist`
- [x] Smoke test tarball (at least install + enable)
- [x] Upload to marketplace
- [x] Publish for customers
- [x] Send mail to release-coordination with link to this ticket and to the changelog
- [x] Rename QA milestone to '$version'
- [x] Add a new 'Unreleased' section in CHANGELOG.md
- [x] Create PR to merge changes back to the `master` branch => https://github.com/owncloud/announcementcenter/pull/110

**Comment by PVince81** [comment]
@DeepDiver1975 please upload https://cloud.owncloud.com/index.php/s/2y8pXFe3peVxFpZ
changelog here: https://github.com/owncloud/announcementcenter/blob/release-1.2.1/CHANGELOG.md#121

**Comment by DeepDiver1975** [comment]
released
