### ISSUE TITLE
Error when enabling app

### ISSUE THREAD

**Issue by dsoap** [owncloud/announcementcenter#31]
I get the following error when trying to enable this app: 
```
An exception occurred while executing 'CREATE TABLE `oc_announcements` (`announcement_id` INT AUTO_INCREMENT NOT NULL, `announcement_time` INT DEFAULT 0 NOT NULL, `announcement_user` VARCHAR(64) NOT NULL, `announcement_subject` VARCHAR(512) NOT NULL, `announcement_message` VARCHAR(64000) DEFAULT NULL, PRIMARY KEY(`announcement_id`)) DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ENGINE = InnoDB': SQLSTATE[42000]: Syntax error or access violation: 1074 Column length too big for column 'announcement_message' (max = 21845); use BLOB or TEXT instead
```

I have even tried to create the database myself and it has not worked to resolve this issue.
```
mysql> desc oc_announcements;
+----------------------+--------------+------+-----+---------+----------------+
| Field                | Type         | Null | Key | Default | Extra          |
+----------------------+--------------+------+-----+---------+----------------+
| announcement_id      | int(11)      | NO   | PRI | NULL    | auto_increment |
| announcement_time    | int(11)      | NO   |     | 0       |                |
| announcement_user    | varchar(64)  | NO   |     | NULL    |                |
| announcement_subject | varchar(512) | NO   |     | NULL    |                |
| announcement_message | text         | YES  |     | NULL    |                |
+----------------------+--------------+------+-----+---------+----------------+
5 rows in set (0.00 sec)
```

**Comment by nickvergessen** [comment]
Please use the issue template:
https://raw.githubusercontent.com/owncloud/core/master/issue_template.md

at least the mysql version is of large interest

**Comment by dsoap** [comment]
### Steps to reproduce
1. Have tried multiple times to click enable on the app  
2. Created the database table manually

### Expected behaviour
The announcement app should enable but it is throwing an error

### Actual behaviour
An exception occurred while executing 'CREATE TABLE `oc_announcements` (`announcement_id` INT AUTO_INCREMENT NOT NULL, `announcement_time` INT DEFAULT 0 NOT NULL, `announcement_user` VARCHAR(64) NOT NULL, `announcement_subject` VARCHAR(512) NOT NULL, `announcement_message` VARCHAR(64000) DEFAULT NULL, PRIMARY KEY(`announcement_id`)) DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ENGINE = InnoDB': SQLSTATE[42000]: Syntax error or access violation: 1074 Column length too big for column 'announcement_message' (max = 21845); use BLOB or TEXT instead

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
mysql  Ver 14.14 Distrib 5.5.46,

**PHP version:**
PHP 5.5.9-1ubuntu4.14

**ownCloud version:** (see ownCloud admin page)
8.2.1.4 (stable)

**Updated from an older ownCloud or fresh install:**
Updated from older version

**List of activated apps:**
- activity: 2.1.3
  - calendar: 0.8.1
  - contacts: 0.5.0.0
  - documents: 0.11.0
  - files: 1.2.0
  - files_external: 0.3.0
  - files_locking: 
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - files_videoviewer: 0.1.3
  - firstrunwizard: 1.1
  - gallery: 14.2.0
  - ownnote: 1.05
  - provisioning_api: 0.3.0
  - qownnotesapi: 0.4.1
  - templateeditor: 0.1
  - updater: 0.6
