### ISSUE TITLE
Move Announcements from "Apps" to "User-Menu"

### ISSUE THREAD

**Issue by aspdye** [owncloud/announcementcenter#33]
I think it should be an point in the menu "Personal - Help - Admin - Users - Announcements" and not as an app like Calendar, Contacts because it isnt an "real" app ;)

**Comment by nickvergessen** [comment]
Well it well be when we have comments and other things I have in my mind for the app.
Also the option to make announcements the first app when logging in and stuff like that.
So we will not change that
