### ISSUE TITLE
Better Style in Notification-Center

### ISSUE THREAD

**Issue by aspdye** [owncloud/announcementcenter#47]
Hi there,

I think we should:

- make the title of the announcement bold
- maybe show user-picture in front of "username has announced ..."
- date of announcement

**Comment by nickvergessen** [comment]
Notifications have no HTML support as of yet, because they will also be shown on the client.
As for the date, we could show the date of when the notification was triggered, but that should be reported at  https://github.com/owncloud/notifications/issues
