### ISSUE TITLE
Impact on mail notifications 

### ISSUE THREAD

**Issue by avv-owncloud** [owncloud/announcementcenter#53]
Hello,
Currently running OC 8.2.2 and Annoucements 1.0.1
I noticed that publishing a new announcement puts entries in oc_activity_mq... and prevent any further mail notification to happen.

Diag: the EMail notification job disappears

Temp solution: purge the table from all announcement entries, re-create the cron job

Log: All I found in the log was:
{"reqId":"3jE\/yF5UrDkt1B1SfJtf","remoteAddr":"","app":"no app in context","message":"Error while running background job: The token is invalid","level":3,"time":"2016-03-06T13:39:03+00:00"} 

Queue:
I checked the oc_activity_mq
- amq_appid was announcement
- amq_subject was announcement

Quick thought (not sure of course): it seems OC looked for a template and/or application to generate the related mails but  did not find anything and splashed

Get in touch if you need more information, and thank you for the job already done.

**Comment by avv-owncloud** [comment]
Excerpt from the oc_activity_mq table:

+---------+---------------+-----------------+--------------------+------------------+--------------------+-----------------------+-------------------+
| mail_id | amq_timestamp | amq_latest_send | amq_type           | amq_affecteduser | amq_appid          | amq_subject           | amq_subjectparams |
+---------+---------------+-----------------+--------------------+------------------+--------------------+-----------------------+-------------------+
|    1982 |    1457344542 |      1457348142 | announcementcenter | SomeUserName             | announcementcenter | announcementsubject#6 | ["myadminaccount"]        |

**Comment by nickvergessen** [comment]
hi @avv-owncloud I seem to have found the issue, can you test whether https://github.com/owncloud/announcementcenter/pull/55 helps?

**Comment by avv-owncloud** [comment]
Hey there.
Just tested right now.

Activity message to the admin (announcer) and users seem to be ok, 
pushing the announcement title to the mail message.
The activity "generator" is the same in both cases (meaning the admin, 
and not "You" if you receive the mail as admin as well); which is 
consistent with the proposed trick.

    See excerpt from the mail (no worry about the format, I hooked to
    have an html-based layout
    Hello AvV (Boss),

    You are receiving this email because the following things happened at /

      * AvV (Boss) announced Mail notification: fixed - Today at 4:28:47 PM



Very first good point: no more corruption of the job table, and message 
sent to users.

Looking forward to your next version, since this is a nice tool.

Thanks.

On 03/07/2016 04:46 PM, Joas Schilling wrote:
>
> hi @avv-owncloud <https://github.com/avv-owncloud> I seem to have 
> found the issue, can you test whether #55 
> <https://github.com/owncloud/announcementcenter/pull/55> helps?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/owncloud/announcementcenter/issues/53#issuecomment-193306332>.
>

Cordialement,

AvV

	Alain van Volden
avv@av2.solutions

**Comment by nickvergessen** [comment]
Yeah, that is what we have to live with, until I have a proper fix. But atleast emails work again

**Comment by avv-owncloud** [comment]
Indeed.

The announcer is the admin, so no real worry

Thank you for your quick reaction and this fix :)


On 03/07/2016 06:03 PM, Joas Schilling wrote:
>
> Yeah, that is what we have to live with, until I have a proper fix. 
> But atleast emails work again
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/owncloud/announcementcenter/issues/53#issuecomment-193346810>.
>

Cordialement,

AvV

	Alain van Volden
avv@av2.solutions

**Comment by nickvergessen** [comment]
Released new version 1.0.2 (8.2) and 1.1.1 (9.0) in the app store just now:
https://apps.owncloud.com/content/show.php/Announcement+Center?content=173921
