### ISSUE TITLE
Announcement Center is marked as "Experimental"

### ISSUE THREAD

**Issue by aspdye** [owncloud/announcementcenter#59]
Happens since ownCloud 9.0.0 :unamused:

**Comment by nickvergessen** [comment]
@LukasReschke I thought this does not happen for signed apps?

**Comment by LukasReschke** [comment]
> @LukasReschke I thought this does not happen for signed apps?

Nope. It's unrelated, the only thing that signed ensures is that it _can_ have the tag "Official". The whole other rating stuff has still to be applied at each update :see_no_evil:

**Comment by LukasReschke** [comment]
Should be corrected now. I changed the flags again.

**Comment by nickvergessen** [comment]
Arg okay will modify me release list then
