### ISSUE TITLE
Announcementcenter is listing only the last 5 announcements

### ISSUE THREAD

**Issue by apg1980** [owncloud/announcementcenter#67]
Is there a adjustement to show all announcements?

**Comment by nickvergessen** [comment]
For now you can easily adjust it in the code:
https://github.com/owncloud/announcementcenter/blob/5d4d3e3e045ab130e309bee0bf98e89af10e0c33/controller/pagecontroller.php#L41-L41

But yeah, we should add some scrolling detection to that.
