### ISSUE TITLE
Question: Show all Notifications

### ISSUE THREAD

**Issue by apg1980** [owncloud/announcementcenter#71]
Question: Is there a possibility to show all recent notifcations in a user sight?
This time only last few notifications are shown, but not all recent.
I notify my users about changes, howtos etc. They cannot see that old posts anymore.

**Comment by nickvergessen** [comment]
See #67 I fixed it by adding pagination:
https://github.com/owncloud/announcementcenter/pull/68

Once I do the next release it should be included.

**Comment by apg1980** [comment]
when will it come? thanks for that

**Comment by nickvergessen** [comment]
Just did it:
https://twitter.com/nickvergessen/status/723445567066505216
