### ISSUE TITLE
Label doesn't shown up on new announcements!!!

### ISSUE THREAD

**Issue by messalas** [owncloud/announcementcenter#90]
The label doesn't appear any more when I post a new announcement in the announcementcenter!!!

### Server configuration
**Operating system**: Ubuntu 16.04

**Web server:** Apache2

**Database:** MySQL

**PHP version:** PHP Version 7.0.22-0ubuntu0.16.04.1

**ownCloud version:** 10.0.3.3

**Updated from an older ownCloud or fresh install:** fresh

**Where did you install ownCloud from:** owncloud

**Signing status (ownCloud 9.0 and above):** No errors have been found.

**Comment by DeepDiver1975** [comment]
Did you run cron? Whats your cron mode?

**Comment by messalas** [comment]
the notification label is visible after some time..
