### ISSUE TITLE
php-cs-fixer

### ISSUE THREAD

**Issue by mmattel** [owncloud/announcementcenter#95]
@DeepDiver1975 
Any plans to implement ``php-cs-fixer`` as we have in core ?

**Comment by phil-davis** [comment]
PR #97 has one attempt. Look in the comments there. It might be easiest to copy parts ffrom there and make a new PR to "current" conventions.

**Comment by dpakach** [comment]
Added php-cs-fixer and also make targets in #104

**Comment by phil-davis** [comment]
See issue #105 and PR #106 which implement this.
